version: '2'

services:
  worksonmymachine:
    image: username/worksonmymachine:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "8080:80"
    volumes:
      - .:/app
